Minor layout corrections
projectcaluma/caluma-demo pull request #38
Opened 2019-10-09 07:48 UTC by JohnL17

2019-10-15 14:19 UTC, kaldras requested changes

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/app/helpers/trim-description.js
> +  const [passedString, length] = params;
`length` isn't used anywhere. Should probably be used on line 5 instead of the hardcoded `150`

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/app/routes/documents/edit.js
> +    controller.set("model", model);
Is this needed? Isn't this done by the `_super` call?

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/app/templates/documents/index.hbs
> +  <p class="uk-text-center">{{t "documents.not-found"}}</p>
I would add the "not found" message as a single table row in the actual table where you are rendering the entries and not duplicate a whole table for nothing! The `{{each}}` also has an `{{else}}` part.

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/app/templates/documents/new.hbs
> +              {{trim-description form.node.description 170}}
Why is the description here longer than on `documents/index`? Try to keep one field consistent over the application.

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/tests/integration/helpers/trim-description-test.js
> +    assert.equal(this.element.textContent.trim(), "1234");
The test would be more useful if we actually test if it is trimming the text. ;)

2019-10-15 14:19 UTC, kaldras commented on caluma-demo/tests/integration/helpers/trim-title-test.js
> +module("Integration | Helper | trim-title", function(hooks) {
I can't find a `trim-title` helper! Is this obsolete?

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/tests/integration/helpers/trim-title-test.js
> +module("Integration | Helper | trim-title", function(hooks) {
Yes it is. I forgot to delete it.

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/tests/integration/helpers/trim-description-test.js
> +    assert.equal(this.element.textContent.trim(), "1234");
I wrote an actual test for the trimming helper.

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/app/templates/documents/new.hbs
> +              {{trim-description form.node.description 170}}
Done.

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/app/templates/documents/index.hbs
> +  <p class="uk-text-center">{{t "documents.not-found"}}</p>
I've changed it.

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/app/routes/documents/edit.js
> +    controller.set("model", model);
As discussed.

2019-10-15 15:12 UTC, JohnL17 commented on caluma-demo/app/helpers/trim-description.js
> +  const [passedString, length] = params;
I forgot to replace the hardcoded integer with the variable. ;-)

2019-10-16 08:57 UTC, anehx commented on caluma-demo/app/routes/documents/edit.js
> +    this._super(controller, model);
```suggestion
    super.setupController(...arguments);
```

2019-10-16 09:13 UTC, kaldras commented on caluma-demo/app/routes/documents/edit.js
> +    controller.set("model", model);
See the comment from @anehx . With this change you can remove this line.

2019-10-16 11:40 UTC, kaldras commented on caluma-demo/translations/en.yaml
> +  not-found: We did not find any documents. Click the button beneath to create a new document right now!
The button is `above`

2019-10-17 10:55 UTC, JohnL17 commented on caluma-demo/app/routes/documents/edit.js
> +    controller.set("model", model);
I have changed the super and removed this line.

2019-10-17 10:55 UTC, JohnL17 commented on caluma-demo/app/routes/documents/edit.js
> +    this._super(controller, model);
Done.

2019-10-17 10:55 UTC, JohnL17 commented on caluma-demo/translations/en.yaml
> +  not-found: We did not find any documents. Click the button beneath to create a new document right now!
Ah right ;-)

2019-10-17 11:10 UTC, kaldras approved these changes

2019-10-17 11:11 UTC, merged